version: '3.8'

services:


  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  app:
    container_name: app
    build: .
    image: calebsideras/tweetailyze-app:latest
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always

  redis:
    container_name: redis
    image: redis:7.2-rc-alpine

  celery_worker:
    container_name: celery_worker
    build: .
    image: calebsideras/tweetailyze-celery_worker:latest
    command: celery -A celery_worker.celery worker --loglevel=info
    volumes:
    - .:/app
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - app
      - redis

  caddy:
    build: ./caddy
    image: caddy:2.6.4
    ports:
      - 443:443
      - 80:80
    privileged: true
    depends_on:
      - app